# Generated by Django 4.2.13 on 2024-05-14 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lms_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="member",
            old_name="outstanding_dept",
            new_name="outstanding_debt",
        ),
    ]
